[workspace]
members = ["tower-mqtt","tower-raft","tower"]

[workspace.package]
name = "ThingsTower"
version = "0.1.0"
edition = "2021"
authors = ["gsxhnd"]
homepage = ""
description = "MQTT Server for v3.1, v3.1.1 and v5.0 protocols"
repository = "https://github.com/gsxhnd/ThingsTower"
license = "MIT license"
categories = ["network"]
keywords = ["MQTT", "IoT", "messaging", "MQTT Server", "MQTT Broker"]
exclude = [".gitignore", ".cargo/config"]
rust-version = "1.68"


[path]
tower_mqtt = { path ="tower-mqtt" }
tower_raft = { path ="tower-raft" }

[workspace.dependencies]
axum = {version = "0.6"}
bytes = { version = "1.4", features = ["serde"] }
clap = { version = "4.3", features = ["derive","env"] }
futures = { version = "0.3" }
futures-util = { version = "0.3" }
mqttrs = { version = "0.4.1", features = [ "derive" ] }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
tokio = { version = "1.28", features = ["full"] }
tokio-util = {version = "0.7", features = ["codec"]}
tokio-stream = "0.1.14"
tokio-tungstenite = { version= "0.19" }
tracing = {version = "0.1"}
tracing-subscriber = "0.3"