//! Events emitted by the MQTT client.

use bytes::Bytes;

/// Events received from the broker or generated by the client.
#[derive(Debug, Clone)]
pub enum Event {
    /// Successfully connected to the broker.
    Connected {
        /// Whether the broker restored a previous session.
        session_present: bool,
    },

    /// Attempting to reconnect after an unexpected disconnect.
    Reconnecting {
        /// 1-based reconnect attempt number.
        attempt: u32,
        /// Delay before this attempt.
        delay_ms: u64,
    },

    /// Received a PUBLISH message from the broker.
    Message {
        topic: String,
        payload: Bytes,
        qos: u8,
        retain: bool,
    },

    /// A PUBLISH (QoS 1) was acknowledged by the broker.
    PubAck { packet_id: u16 },

    /// A PUBLISH (QoS 2) completed the full handshake.
    PubComp { packet_id: u16 },

    /// Subscription confirmed by the broker.
    SubAck {
        packet_id: u16,
        return_codes: Vec<u8>,
    },

    /// Unsubscription confirmed by the broker.
    UnsubAck { packet_id: u16 },

    /// The connection was lost (or a graceful disconnect completed).
    Disconnected { reason: Option<String> },
}
